name: run-tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    env:
      CACHE_DEPENDENCY_PATH: setup/requirements-unittest.txt
      PYTHON_VERSION: 3.9.12 # use cached Python version in ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '${{ env.PYTHON_VERSION }}'
          cache: 'pip'
          cache-dependency-path: '${{ env.CACHE_DEPENDENCY_PATH }}'
      - run: pip install -r ${{ env.CACHE_DEPENDENCY_PATH }}
      - run: python -m unittest -v
      - run: sleep 30
      - run: echo "hello, world B"

